export interface ISong {
    track_id: string;
    track_name: string;
    track_artist: string;
    played_at: string[];
    explicit: boolean;
    popularity: number;
    album: string;
    album_cover: string;
    album_cover_height: number;
    album_cover_width: number;
    duration: number;
    loudness: number;
    tempo: number;
    key: number;
    time_signature: number;
    mode: number;
    acousticness: number;
    danceability: number;
    energy: number;
    instrumentalness: number;
    speechiness: number;
    valence: number;
    sections: number;
    section_duration_avg: number;
    loudness_avg: number;
    tempo_avg: number;
    start_sequence: number[];
    loudness_sequence: number[];
    tempo_sequence: number[];
    key_sequence: number[];
    mode_sequence: number[];
    time_signature_sequence: number[];
}

export class Song {
    public trackId: string;
    public trackName: string;
    public trackArtist: string;
    public playedAt: string[];
    public explicit: boolean;
    public popularity: number;
    public album: string;
    public albumCover: string;
    public albumCoverHeight: number;
    public albumCoverWidth: number;
    public duration: number;
    public loudness: number;
    public tempo: number;
    public key: number;
    public timeSignature: number;
    public mode: number;
    public acousticness: number;
    public danceability: number;
    public energy: number;
    public instrumentalness: number;
    public speechiness: number;
    public valence: number;
    public sections: number;
    public sectionDurationAvg: number;
    public loudnessAvg: number;
    public tempoAvg: number;
    public startSequence: number[];
    public loudnessSequence: number[];
    public tempoSequence: number[];
    public keySequence: number[];
    public modeSequence: number[];
    public timeSignatureSequence: number[];

    public constructor(data: ISong) {
        this.trackId = data.track_id;
        this.trackName = data.track_name;
        this.trackArtist = data.track_artist;
        this.playedAt = data.played_at;
        this.explicit = data.explicit;
        this.popularity = data.popularity;
        this.album = data.album;
        this.albumCover = data.album_cover;
        this.albumCoverHeight = data.album_cover_height;
        this.albumCoverWidth = data.album_cover_width;
        this.duration = data.duration;
        this.loudness = data.loudness;
        this.tempo = data.tempo;
        this.key = data.key;
        this.timeSignature = data.time_signature;
        this.mode = data.mode;
        this.acousticness = data.acousticness;
        this.danceability = data.danceability;
        this.energy = data.energy;
        this.instrumentalness = data.instrumentalness;
        this.speechiness = data.speechiness;
        this.valence = data.valence;
        this.sections = data.sections;
        this.sectionDurationAvg = data.section_duration_avg;
        this.loudnessAvg = data.loudness_avg;
        this.tempoAvg = data.tempo_avg;
        this.startSequence = data.start_sequence;
        this.loudnessSequence = data.loudness_sequence;
        this.tempoSequence = data.tempo_sequence;
        this.keySequence = data.key_sequence;
        this.modeSequence = data.mode_sequence;
        this.timeSignatureSequence = data.time_signature_sequence;
    }
}